# Schema for the configuration files of the queue worker module.
article_queue.settings:
  type: config_object
  label: 'queue worker settings'
  mapping:
    example:
      type: string
      label: 'Example'
